name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: release

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        COINSPOT_API_KEY: ${{ secrets.COINSPOT_API_KEY }}
        COINSPOT_API_SECRET: ${{ secrets.COINSPOT_API_SECRET }}
      run: |
        pytest
